services:
  # 1. Konfigurasi Web Service (Aplikasi Rails kamu)
  - type: web
    name: ruby-minimarket
    runtime: ruby
    plan: free # atau starter
    buildCommand: "./bin/render-build.sh"
    startCommand: "bundle exec rails server"
    envVars:
      - key: DATABASE_URL
        fromDatabase:
          name: minimarket-db
          property: connectionString
      - key: RAILS_MASTER_KEY
        sync: false
      - key: RAILS_MAX_THREADS
        value: "5"

# 2. Konfigurasi Database PostgreSQL
databases:
  - name: minimarket-db
    databaseName: ruby_minimarket_production # Opsional, Render akan buatkan otomatis jika kosong
    plan: free # atau starter