default: &default
  adapter: postgresql 
  encoding: unicode
  pool: <%= ENV.fetch("RAILS_MAX_THREADS") { 5 } %> 
  username: annisanursalamah 
  password: selaluceria
  host: localhost
  port: 5432

development:
  <<: *default
  database: ruby_minimarket_development
  pool: 35
  
test:
  <<: *default
  database: ruby_minimarket_test

production:
  <<: *default
  # Render secara otomatis menyediakan environment variable DATABASE_URL
  url: <%= ENV['DATABASE_URL'] %>
  # Hapus database, username, dan password manual karena sudah tercakup di dalam DATABASE_URL